"""MQTT Client Constants - Default configuration values"""

DEFAULT_BROKER = "localhost"
DEFAULT_PORT = 1883
DEFAULT_TOPIC = "xagent/data"
DEFAULT_COMMAND_TOPIC = "xagent/command"
DEFAULT_CLIENT_ID = "xagent_mqtt_uploader"
DEFAULT_QOS = 1
DEFAULT_KEEPALIVE = 60
DEFAULT_PUBLISH_MODE = "single"
DEFAULT_BATCH_SIZE = 100
DEFAULT_INTERVAL = 5
DEFAULT_RECONNECT_INTERVAL = 5
DEFAULT_RECONNECT_MAX_DELAY = 60
DEFAULT_RETRY_COUNT = 3
DEFAULT_RETRY_DELAY = 1

PUBLISH_MODE_SINGLE = "single"
PUBLISH_MODE_BATCH = "batch"
