"""XNC Client Constants - Default configuration values"""

DEFAULT_REMOTE_HOST = "127.0.0.1"
DEFAULT_REMOTE_PORT = 9000
DEFAULT_LOCAL_PORT = 8888
DEFAULT_BATCH_SIZE = 100
DEFAULT_INTERVAL = 5
DEFAULT_RECONNECT_INTERVAL = 5

PROTOCOL_MODE_JSON = "json"
PROTOCOL_MODE_PROTOBUF = "protobuf"
